"""add feature image url in post table

Revision ID: 1133d983cd5d
Revises: a05a61804d73
Create Date: 2025-01-08 09:45:27.884522

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1133d983cd5d'
down_revision = 'a05a61804d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('feature_image_url', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'feature_image_url')
    # ### end Alembic commands ###
