"""modify unique(is_published, title) instead of title only

Revision ID: 288629a61cbe
Revises: bede948ae450
Create Date: 2025-01-27 21:47:15.018914

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '288629a61cbe'
down_revision = 'bede948ae450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_title_key', 'post', type_='unique')
    op.create_unique_constraint('uq_post_is_published_title', 'post', ['is_published', 'title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_is_published_title', 'post', type_='unique')
    op.create_unique_constraint('post_title_key', 'post', ['title'])
    # ### end Alembic commands ###
