"""create tag tables and post relationship

Revision ID: 5854a4cdb988
Revises: 620c04cef3a5
Create Date: 2025-01-24 16:06:21.031844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import uuid


# revision identifiers, used by Alembic.
revision = '5854a4cdb988'
down_revision = '620c04cef3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('post_tag',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_index('ix_post_tag_post_id', 'post_tag', ['post_id'], unique=False)
    op.create_index('ix_post_tag_tag_id', 'post_tag', ['tag_id'], unique=False)
    initial_tags = [
        'backend',
        'frontend',
        'html/css',
        'productivity',
        'fastapi',
        'typescript',
        'javascript',
        'python',
    ]
    
    op.execute(
        """
        INSERT INTO tag (id, name)
        VALUES {}
        """.format(
            ','.join([f"('{uuid.uuid4()}', '{tag}')" for tag in initial_tags])
        )
    )
    op.drop_column('post', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index('ix_post_tag_tag_id', table_name='post_tag')
    op.drop_index('ix_post_tag_post_id', table_name='post_tag')
    op.drop_table('post_tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
