"""add slug column in post table

Revision ID: bede948ae450
Revises: 5854a4cdb988
Create Date: 2025-01-26 01:57:44.904426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bede948ae450'
down_revision = '5854a4cdb988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'post', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
