"""remove items field from user table

Revision ID: dbdee1bed036
Revises: 97fe6fa7dff6
Create Date: 2024-12-10 12:49:01.095540

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dbdee1bed036'
down_revision = '97fe6fa7dff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
